import type { FinanceData } from "@/types";
import { DEFAULT_QUICK_LOG_BUTTONS } from "./constants";

export function getDefaultFinanceData(): FinanceData {
  return {
    accounts: {
      cibc_chequing: 153.05,
      cibc_credit: -83.3,
      bmo_chequing: 2.05,
      bmo_loc: -45000,
      osap: 0,
    },
    income_sources: [
      { id: "is-purolator", name: "Purolator", rate: 21.56, hours: 15, active: true },
      { id: "is-cms", name: "CMS (Jennifer)", rate: 0, hours: 20, active: true },
      { id: "is-tutoring", name: "Tutoring (Tyson)", rate: 35, hours: 2, active: true },
    ],
    fixed_expenses: [
      { id: "fe-fido", name: "Fido Phone", amount: 59.89, due: "23" },
      { id: "fe-google", name: "Google Cloud", amount: 1.99, due: "1" },
      { id: "fe-apple", name: "Apple Storage", amount: 1.99, due: "1" },
    ],
    recurring_transactions: [
      {
        id: "rec-purolator",
        type: "income",
        name: "Purolator",
        default_amount: 323.4,
        frequency: "weekly",
        day_of_week: 1,
        account: "cibc_chequing",
        category: "Salary",
        start_date: "2026-04-06",
        active: true,
        notes: "$21.56/hr x 15hrs",
      },
      {
        id: "rec-cms",
        type: "income",
        name: "CMS (Jennifer)",
        default_amount: 0,
        frequency: "weekly",
        day_of_week: 1,
        account: "cibc_chequing",
        category: "Salary",
        start_date: "2026-03-31",
        active: true,
        notes: "Rate TBD",
      },
      {
        id: "rec-tutoring",
        type: "income",
        name: "Tutoring (Tyson)",
        default_amount: 35,
        frequency: "weekly",
        days_of_week: [1, 5],
        account: "cibc_chequing",
        category: "Tutoring",
        start_date: "2026-03-31",
        active: true,
        notes: "$35/session",
      },
      {
        id: "rec-fido",
        type: "expense",
        name: "Fido Phone",
        default_amount: 59.89,
        frequency: "monthly",
        day_of_month: 23,
        account: "cibc_chequing",
        category: "Phone",
        start_date: "2026-03-23",
        active: true,
        notes: "",
      },
      {
        id: "rec-google-cloud",
        type: "expense",
        name: "Google Cloud",
        default_amount: 1.99,
        frequency: "monthly",
        day_of_month: 1,
        account: "cibc_chequing",
        category: "Subscriptions",
        start_date: "2026-04-01",
        active: true,
        notes: "",
      },
      {
        id: "rec-apple-storage",
        type: "expense",
        name: "Apple Storage",
        default_amount: 1.99,
        frequency: "monthly",
        day_of_month: 1,
        account: "cibc_chequing",
        category: "Subscriptions",
        start_date: "2026-04-01",
        active: true,
        notes: "",
      },
      {
        id: "rec-bmo-loc-interest",
        type: "expense",
        name: "BMO LOC Interest",
        default_amount: 0,
        frequency: "monthly",
        day_of_month: 1,
        account: "bmo_loc",
        category: "Loan Interest",
        start_date: "2026-04-01",
        active: true,
        notes: "Auto-calculated: balance x rate / 12",
      },
    ],
    transactions: [],
    settings: {
      loc_rate: 7.95,
      split: { loc: 40, move: 40, personal: 20 },
      move_target: 8000,
      move_saved: 0,
      osap_deferred_until: "2026-06-01",
      theme: "light",
    },
    monthly_snapshots: [],
    quick_log_buttons: DEFAULT_QUICK_LOG_BUTTONS,
  };
}
